# escape=`

# Runtime (Windows Server 2019)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-windowsservercore-ltsc2019 AS base
WORKDIR /app
EXPOSE 80

# Build (Windows Server 2019)
FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2019 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Пути относительно корня решения (контекст docker build = корень решения)
COPY ["WebApi_ApplicationService/WebApi_applications.csproj", "WebApi_ApplicationService/"]
COPY ["2_KameraData/KameraData.csproj", "2_KameraData/"]
COPY ["SharedMicroserviceLibrary/SharedMicroserviceLibrary.csproj", "SharedMicroserviceLibrary/"]

RUN dotnet restore "WebApi_ApplicationService/WebApi_applications.csproj"

COPY . .
WORKDIR /src/WebApi_ApplicationService
RUN dotnet build "WebApi_applications.csproj" -c %BUILD_CONFIGURATION% -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "WebApi_applications.csproj" -c %BUILD_CONFIGURATION% -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# чтобы 100% слушало 80 (на всякий случай)
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "WebApi_applications.dll"]
